name: 'Create project'
inputs:
  destination:
    description: 'Users repo to create the project'
    required: true
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
  file:
    description: 'The structure of the project in JSON a file.'
    required: true
runs:
  using: 'node12'
  main: 'project.js'
